/*
* ============================================================================
*  Name        : bld.inf
*  Part of     : Alfred UI Toolkit
*  Description : Build information file for project alfappserver
*  Version     : %version: 2 %
*
*  Copyright © 2006 Nokia.  All rights reserved.
*  This material, including documentation and any related computer
*  programs, is protected by copyright controlled by Nokia.  All
*  rights are reserved.  Copying, including reproducing, storing,
*  adapting or translating, any or all of this material requires the
*  prior written consent of Nokia.  This material also contains
*  confidential information which may not be disclosed to others
*  without the prior written consent of Nokia.
* ============================================================================
* Template version: 4.1
*/

#include <bldvariant.hrh>
PRJ_TESTMMPFILES
alfclientstatic_extended_visual.mmp

UT_CAlfLCTTextVisual.mmp
UT_CAlfLCTAnchorLayout.mmp
UT_CAlfLCTGridLayout.mmp


