#include <bldvariant.hrh>		
#include "../../../../uiacceltk/hitchcock/commoninc/alfuids.h"

USERINCLUDE             ../../../../uiacceltk/hitchcock/client/inc
USERINCLUDE             ../../../../uiacceltk/hitchcock/commoninc


#include <platform_paths.hrh>
MW_LAYER_SYSTEMINCLUDE

LIBRARY                 apgrfx.lib
LIBRARY                 apparc.lib
LIBRARY                 avkon.lib
LIBRARY                 cone.lib
LIBRARY                 efsrv.lib
LIBRARY                 eikcore.lib
LIBRARY                 EUnit.lib
LIBRARY                 euser.lib
LIBRARY                 fbscli.lib
LIBRARY                 flogger.lib
LIBRARY                 ImageConversion.lib
LIBRARY                 ws32.lib
LIBRARY                 aknicon.lib
LIBRARY                 hal.lib
LIBRARY                 bitgdi.lib
LIBRARY                 ftokenclient.lib
LIBRARY                 gdi.lib 
LIBRARY                 hwrmlightclient.lib
LIBRARY                 aknskins.lib
LIBRARY                 SvgEngine.lib

LIBRARY                 aknlayout2hierarchy.lib
LIBRARY                 aknfepuiinterface.lib



STATICLIBRARY alfclientstatic_extended_visual.lib

// End of file
